#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run_desktop"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

IFS=:
dirs="$HOME/.local/share/applications:/usr/share/applications"

# Check if cache needs to be updated or can be used
if stest -dqr -n "$cache" $PATH; then
    # Update cache by searching for applications and filtering results
    stest -fl $dirs | grep -v 'mimeinfo.cache' | grep -v 'recently-used' | sed '/org.telegram.desktop.desktop/!s/\.[^./]*$//' | tee "$cache"
else
    cat "$cache"
fi

selected=$(dmenu "$@" < "$cache" | xargs)
[ -n "$selected" ] && gtk-launch "$selected" &
